//! An example library crate.

// In a real library you'd do this unconditionally.  But since this is part of the jni-bindgen workspace, and I don't
// want to force the user to compile tens of thousands of lines of autogenerated android bindings, I've gated this
// behind a non-default feature.
#[cfg(feature = "gen")] include!("gen.rs");
