// WARNING:  This file was autogenerated by jni-bindgen.  Any changes to this file may be lost!!!

#[allow(unused_imports)] #[macro_use(__jni_bindgen)] extern crate jni_glue;
#[doc(hidden)] use jni_glue as __jni_bindgen;
